# Generated by Django 6.0.1 on 2026-01-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_path', models.CharField(blank=True, default='', help_text='Absolute path where reports are saved locally.', max_length=500)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
