# Generated by Django 6.0.1 on 2026-02-09 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
