# Generated by Django 6.0.1 on 2026-01-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidationtask',
            name='log_message',
        ),
        migrations.AddField(
            model_name='consolidationtask',
            name='processing_log',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='consolidationtask',
            name='input_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='consolidationtask',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='outputs/'),
        ),
        migrations.AlterField(
            model_name='consolidationtask',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
