# Generated by Django 6.0.1 on 2026-01-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidation', '0002_remove_consolidationtask_log_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidationtask',
            name='error_file',
            field=models.FileField(blank=True, null=True, upload_to='error_reports/'),
        ),
        migrations.AddField(
            model_name='consolidationtask',
            name='log_message',
            field=models.TextField(blank=True),
        ),
    ]
