# Generated by Django 6.0.1 on 2026-01-27 10:02

import consolidation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidation', '0003_consolidationtask_error_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidationtask',
            name='error_file',
        ),
        migrations.AlterField(
            model_name='consolidationtask',
            name='input_file',
            field=models.FileField(upload_to=consolidation.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='consolidationtask',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='consolidationtask',
            name='processing_log',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='consolidationtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
