# Generated by Django 6.0.1 on 2026-01-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consolidation', '0004_remove_consolidationtask_error_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidationtask',
            name='processing_log',
        ),
    ]
