# Generated by Django 6.0.1 on 2026-01-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovatr', models.CharField(max_length=50, unique=True, verbose_name='Session/OVATR Code')),
                ('company_name_kh', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('vatin', models.CharField(blank=True, max_length=50, null=True, verbose_name='VATIN (New)')),
                ('old_vatin', models.CharField(blank=True, max_length=50, null=True, verbose_name='VATIN (Old)')),
                ('enterprise_id', models.CharField(blank=True, max_length=50, null=True)),
                ('file_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_entity', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_date', models.CharField(blank=True, max_length=50, null=True)),
                ('success_date', models.CharField(blank=True, max_length=50, null=True)),
                ('taxpayer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_year', models.CharField(blank=True, max_length=20, null=True)),
                ('address_main', models.TextField(blank=True, null=True)),
                ('address_office', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_count', models.CharField(blank=True, max_length=50, null=True)),
                ('total_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rent_per_month', models.CharField(blank=True, max_length=100, null=True)),
                ('enterprise_form', models.CharField(blank=True, max_length=100, null=True)),
                ('add_ent_form', models.CharField(blank=True, max_length=100, null=True)),
                ('signage', models.CharField(blank=True, max_length=100, null=True)),
                ('h_date', models.CharField(blank=True, max_length=50, null=True)),
                ('h_real_12m', models.CharField(blank=True, max_length=100, null=True)),
                ('h_real_3m', models.CharField(blank=True, max_length=100, null=True)),
                ('h_est_12m', models.CharField(blank=True, max_length=100, null=True)),
                ('h_est_3m', models.CharField(blank=True, max_length=100, null=True)),
                ('business_activities', models.JSONField(blank=True, default=list)),
                ('enterprise_accounts', models.JSONField(blank=True, default=list)),
                ('related_institutions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='ReverseCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovatr', models.CharField(db_index=True, max_length=50)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('document_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vat_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovatr', models.CharField(db_index=True, max_length=50)),
                ('customer_tin', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('non_taxable_sales', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('value_export', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovatr', models.CharField(db_index=True, max_length=50)),
                ('customs_permit_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovatr', models.CharField(db_index=True, max_length=50)),
                ('supplier_tin', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('row_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Purchase Record',
                'indexes': [models.Index(fields=['ovatr', 'supplier_tin', 'invoice_no', 'date'], name='crosscheck__ovatr_104c18_idx')],
            },
        ),
    ]
