# Generated by Django 6.0.1 on 2026-02-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosscheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovatr', models.CharField(max_length=50, unique=True, verbose_name='OVATR Code')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('match_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='crosscheck__ovatr_104c18_idx',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='ReverseCharge',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='TaxPaid',
        ),
    ]
