# Generated by Django 6.0.1 on 2026-02-09 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosscheck', '0002_crosschecksession_delete_companyinfo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrossCheckSession',
        ),
    ]
